{% set name = "mathjax" %}
{% set version = "2.7.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # url: https://github.com/mathjax/MathJax/archive/{{ version }}.tar.gz
  # sha256: a25e5736553eef7b05ba00df133ad36d8f7b3b967f1e32d2f7505ac77427946f
  url: file:///C:/Users/User/Downloads/MathJax/MathJax-2.7.5.zip
  sha256: 0436a775c020bde86bb0af4b1c93fb43fb662e22eca22777d6637cdf3f801725

build:
   number: 0

test:
  commands:
    - mathjax-conda

about:
  home: https://github.com/mathjax/MathJax
  license: "Apache License 2.0"
  license_family: Apache
  license_file: "{{ environ['SRC_DIR'] }}/LICENSE"
  summary: "Beautiful math in all browsers. MathJax is an open-source JavaScript display engine for LaTeX, MathML, and AsciiMath notation that works in all browsers."
  doc_url: https://github.com/mathjax/MathJax
  dev_url: https://github.com/mathjax/MathJax

extra:
  recipe-maintainers:
    - kiwi0fruit
