{% set version = "2.20.1" %}

package:
  name: git-bash
  version: {{ version }}

source:
  # url: https://github.com/git-for-windows/git/releases/download/v{{ version }}.windows.1/PortableGit-{{ version }}-64-bit.7z.exe   # [win64]
  url: file:///C:/Users/User/Downloads/PortableGit-2.20.1-64-bit.7z.exe   # [win64]
  sha256: 4c0fc0c77d577f8dbb3d7711283458ba1d0ce1781cfe0d49c940abbcdf18faa0   # [win64]

build:
  number: 0
  # git hardcodes paths to external utilities (e.g. curl)
  detect_binary_files_with_prefix: true

requirements:
  build:
    - 7za   # [win]

test:
  commands:
    - if not exist %LIBRARY_PREFIX%\\git-bash\\bin\\bash.exe exit 1   # [win]
    - git --version   # [win]
    - git clone https://github.com/conda-forge/git-feedstock   # [win]

about:
  home: https://git-scm.com/
  license: "git: GPLv2, LGPLv2.1, bash: GPLv3+ if Windows else MIT"
  license_file: LICENSE.txt   # [win]
  summary: distributed version control system

extra:
  recipe-maintainers:
    - kiwi0fruit
